/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.Menu;

import java.io.EOFException;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mstava
 */
public final class IngredientReport extends javax.swing.JFrame {
    DefaultTableModel tableModel;
    Date date;
    DateFormat dateformat;
    DateFormat dayDateformat;
    ArrayList<Ingredientsclass> ingredients;
 
 //   Order order;
    String dateString;
    String dayDateString;

    /**
     * Creates new form Report
     */
    public IngredientReport() {
        initComponents();
        tableModel = new DefaultTableModel();
        ingredients = new ArrayList<Ingredientsclass>();
        dateformat = new SimpleDateFormat("dd-MM-yyyy - hh:mm:ss");
        dayDateformat = new SimpleDateFormat("dd-MM-yyyy");
        date = new Date();
        dateString = dateformat.format(date);
        dayDateString = dayDateformat.format(date);
        populatearraylist();
        tableModel = (DefaultTableModel) jTableReport.getModel();
        showReport();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableReport = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingredient Report");

        jTableReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ingredient", "Cost", "Quantity", "Unit", "Total Cost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableReport);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Ingredients Report");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void populatearraylist()
    {
        try
        {
            FileInputStream file= new FileInputStream("ingredients" + dayDateString + ".dat");// to make file 
            try (ObjectInputStream inputFile = new ObjectInputStream(file) //read object from file
            ) {
                boolean endOfFile =false; //to check whether if it's the end of the file
                while(!endOfFile)// it's not the end of the file so keep extracting data
                {
                    try
                    {
                        ingredients.add((Ingredientsclass)inputFile.readObject());// reading from file and add to arraylist
                    
                    }
                    catch(EOFException e) //when end of file
                    {
                        endOfFile=true;
                    }
                    catch(IOException | ClassNotFoundException f)
                    {
                        JOptionPane.showMessageDialog(null,f.getMessage());
                    }
                }
            } //to check whether if it's the end of the file
        }
        catch(IOException e) // if there is no data in the file
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }
    
    
    public void showReport()
    {
 
       tableModel = (DefaultTableModel) jTableReport.getModel();
       for(Ingredientsclass ingredientR: ingredients){
           
           tableModel.addRow(new Object[]{ingredientR.getName(), ingredientR.getCost(),
                            ingredientR.getQuantity(), ingredientR.getUnit(),
                            ingredientR.getCost()*ingredientR.getQuantity()
                            });
       }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngredientReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngredientReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngredientReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngredientReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new IngredientReport().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableReport;
    // End of variables declaration//GEN-END:variables
}
