/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.Menu;
import java.io.*;

/**
 *
 * @author Moshira
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        newOrderMenuItem = new javax.swing.JMenuItem();
        exitFileItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        addSubMenu = new javax.swing.JMenu();
        addIngrMenuItem = new javax.swing.JMenuItem();
        addDishMenuItem = new javax.swing.JMenuItem();
        ingredEditItem = new javax.swing.JMenuItem();
        dishesEditItem = new javax.swing.JMenuItem();
        reportsMenu = new javax.swing.JMenu();
        dishesReportItem = new javax.swing.JMenuItem();
        ingredReportsItem = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Slice Restaurant");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Menu/39441496_2175712579373214_4275658604800901120_n.png"))); // NOI18N

        fileMenu.setText("File");

        jMenu3.setText("New");

        newOrderMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        newOrderMenuItem.setText("Order");
        newOrderMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newOrderMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(newOrderMenuItem);

        fileMenu.add(jMenu3);

        exitFileItem.setText("Exit");
        exitFileItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitFileItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitFileItem);

        jMenuBar1.add(fileMenu);

        editMenu.setBackground(new java.awt.Color(0, 51, 51));
        editMenu.setText("Edit");

        addSubMenu.setText("Add");

        addIngrMenuItem.setText("Ingredient");
        addIngrMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIngrMenuItemActionPerformed(evt);
            }
        });
        addSubMenu.add(addIngrMenuItem);

        addDishMenuItem.setText("Dish");
        addDishMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDishMenuItemActionPerformed(evt);
            }
        });
        addSubMenu.add(addDishMenuItem);

        editMenu.add(addSubMenu);

        ingredEditItem.setText("Ingredients");
        ingredEditItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingredEditItemActionPerformed(evt);
            }
        });
        editMenu.add(ingredEditItem);

        dishesEditItem.setText("Dishes");
        dishesEditItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dishesEditItemActionPerformed(evt);
            }
        });
        editMenu.add(dishesEditItem);

        jMenuBar1.add(editMenu);

        reportsMenu.setText("Reports");

        dishesReportItem.setText("Orders");
        dishesReportItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dishesReportItemActionPerformed(evt);
            }
        });
        reportsMenu.add(dishesReportItem);

        ingredReportsItem.setText("Ingredients ");
        ingredReportsItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingredReportsItemActionPerformed(evt);
            }
        });
        reportsMenu.add(ingredReportsItem);

        jMenuBar1.add(reportsMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingredEditItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingredEditItemActionPerformed
       
    }//GEN-LAST:event_ingredEditItemActionPerformed

    private void dishesEditItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dishesEditItemActionPerformed
         
    }//GEN-LAST:event_dishesEditItemActionPerformed

    private void exitFileItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitFileItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitFileItemActionPerformed

    private void dishesReportItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dishesReportItemActionPerformed
        // TODO add your handling code here:
        new OrderReport().setVisible(true);
    }//GEN-LAST:event_dishesReportItemActionPerformed

    private void addDishMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDishMenuItemActionPerformed
        new Dishes().setVisible(true);
    }//GEN-LAST:event_addDishMenuItemActionPerformed

    private void addIngrMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIngrMenuItemActionPerformed
        new Ingredients().setVisible(true);
    }//GEN-LAST:event_addIngrMenuItemActionPerformed

    private void newOrderMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newOrderMenuItemActionPerformed
        new AddOrder().setVisible(true);
    }//GEN-LAST:event_newOrderMenuItemActionPerformed

    private void ingredReportsItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingredReportsItemActionPerformed
        // TODO add your handling code here:
        new IngredientReport().setVisible(true);
    }//GEN-LAST:event_ingredReportsItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addDishMenuItem;
    private javax.swing.JMenuItem addIngrMenuItem;
    private javax.swing.JMenu addSubMenu;
    private javax.swing.JMenuItem dishesEditItem;
    private javax.swing.JMenuItem dishesReportItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitFileItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem ingredEditItem;
    private javax.swing.JMenuItem ingredReportsItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem newOrderMenuItem;
    private javax.swing.JMenu reportsMenu;
    // End of variables declaration//GEN-END:variables
}
