/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.Menu;

import java.io.EOFException;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mosta
 */
public final class OrderReport extends javax.swing.JFrame {
    DefaultTableModel tableModel;
    Date date;
    DateFormat dayDateformat;
    ArrayList<Dish> dishes;
    ArrayList<Order> ords;
    String dayDateString;
    /**
     * Creates new form OrderReport
     */
    public OrderReport() {
        initComponents();
      //  order = new Order(dateString);
        ords = new ArrayList<Order>();
        tableModel = new DefaultTableModel();
        dishes = new ArrayList<Dish>();
        dayDateformat = new SimpleDateFormat("dd-MM-yyyy");
        date = new Date();
        dayDateString = dayDateformat.format(date);
        populatearraylist();
        tableModel = (DefaultTableModel) orderTbl.getModel();
        showReport();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addDishesLbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderTbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        costOfOrd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        addDishesLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addDishesLbl.setText("Orders' Report");

        orderTbl.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        orderTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "# of Order", "Dish", "Unit Price", "Quantity", "Total Dish Price", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderTbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        orderTbl.setRowHeight(30);
        orderTbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(orderTbl);
        if (orderTbl.getColumnModel().getColumnCount() > 0) {
            orderTbl.getColumnModel().getColumn(0).setMinWidth(80);
            orderTbl.getColumnModel().getColumn(0).setMaxWidth(80);
            orderTbl.getColumnModel().getColumn(1).setMinWidth(180);
            orderTbl.getColumnModel().getColumn(1).setMaxWidth(180);
            orderTbl.getColumnModel().getColumn(2).setMinWidth(150);
            orderTbl.getColumnModel().getColumn(2).setMaxWidth(150);
            orderTbl.getColumnModel().getColumn(3).setMinWidth(80);
            orderTbl.getColumnModel().getColumn(3).setMaxWidth(80);
            orderTbl.getColumnModel().getColumn(4).setMinWidth(150);
            orderTbl.getColumnModel().getColumn(4).setMaxWidth(150);
            orderTbl.getColumnModel().getColumn(5).setMinWidth(150);
            orderTbl.getColumnModel().getColumn(5).setMaxWidth(210);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Total cost of all orders");

        costOfOrd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(addDishesLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                        .addGap(40, 40, 40)
                        .addComponent(costOfOrd, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)))
                .addGap(144, 144, 144))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 849, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(addDishesLbl)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(costOfOrd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void populatearraylist()
    {
        try
        {
            FileInputStream file= new FileInputStream("Orders" + dayDateString +".dat");// to make file 
            ObjectInputStream inputFile = new ObjectInputStream(file); //read object from file
            boolean endOfFile =false; //to check whether if it's the end of the file
            while(!endOfFile)// it's not the end of the file so keep extracting data
            {
                try
                {
                    ords.add((Order)inputFile.readObject());// reading from file and add to arraylist
                }
                catch(EOFException e) //when end of file
                {
                    endOfFile=true;
                }
                catch(Exception f)
                {
                    JOptionPane.showMessageDialog(null,f.getMessage());
                }
            }
            inputFile.close();
        }
        catch(IOException e) // if there is no data in the file
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public void showReport()
    {
       tableModel = (DefaultTableModel) orderTbl.getModel();
       int orderCount = 0;
       double orderPrice = 0;
       double totalCostOfOrders = 0;
        for(Order order: ords)
        {   
            dishes.clear();
            orderCount++;
            orderPrice = 0;
            dishes = order.getDishes();
            for(Dish dish: dishes)
            {
                orderPrice += dish.getQuantity()*dish.getPrice();
            }    
            
            for(Dish dish: dishes)
            {                
                tableModel.addRow(new Object[]{orderCount, dish.getName(), dish.getPrice(), dish.getQuantity(), dish.getQuantity()*dish.getPrice(), order.getDate()});
            }
            totalCostOfOrders += orderPrice;
        }
        costOfOrd.setText(totalCostOfOrders+"");
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addDishesLbl;
    private javax.swing.JLabel costOfOrd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable orderTbl;
    // End of variables declaration//GEN-END:variables
}
